# -*- coding: utf-8 -*-
"""Streamlit dashboard for Generative AI & University Students research.

Reads the raw OpenAlex-style dataset from the Dataset/ folder and the
pre-computed analysis results from the Results/ folder generated by
`generative_ai_university_students_research_analysis_v2_final.py`.
"""

import os
from pathlib import Path

import pandas as pd
import plotly.express as px
import plotly.graph_objects as go
import streamlit as st

try:
    from PIL import Image
except ImportError:
    Image = None

# ------------------------------------------------------------------
# Paths
# ------------------------------------------------------------------
ROOT = Path(__file__).resolve().parent
DATASET_PATH = ROOT / "Dataset" / "works-csv-HFVSQrUPA3cJb2N7qbb7nG (1).csv"
RESULTS_DIR = ROOT / "Results"

# ------------------------------------------------------------------
# Helpers
# ------------------------------------------------------------------
@st.cache_data(show_spinner=False)
def load_csv(path: Path, **kwargs):
    if not path.exists():
        return None
    try:
        return pd.read_csv(path, low_memory=False, **kwargs)
    except Exception as exc:
        st.error(f"Error loading {path.name}: {exc}")
        return None


def result(name: str) -> Path:
    return RESULTS_DIR / name


# ------------------------------------------------------------------
# Page config
# ------------------------------------------------------------------
st.set_page_config(
    page_title="GenAI & University Students Research Dashboard",
    page_icon=None,
    layout="wide",
    initial_sidebar_state="expanded",
)

st.title("Generative AI & University Students: Research Dashboard")
st.markdown(
    "Bibliometric, semantic and social-relational gap analysis of the "
    "university-students generative-AI literature (2022-2026)."
)

# ------------------------------------------------------------------
# Load data
# ------------------------------------------------------------------
dataset = load_csv(DATASET_PATH)
analyzed = load_csv(result("V2_Analyzed_OpenAlex_GenerativeAI_Students.csv"))

concept_freq = load_csv(result("V2_Concept_Frequency.csv"))
dimensions = load_csv(result("V2_Dimension_Coverage.csv"))
gap_test = load_csv(result("V2_Social_Gap_Test.csv"))
social_summary = load_csv(result("V2_Social_Concept_Summary.csv"))
annual_growth = load_csv(result("V2_Annual_Publication_Growth.csv"))
temporal = load_csv(result("V2_Concept_Temporal.csv"))
social_temporal = load_csv(result("V2_Social_Temporal.csv"))
emerging = load_csv(result("V2_Emerging_Theme_Growth.csv"))
tfidf = load_csv(result("V2_TFIDF_Terms.csv"))
lda_topics = load_csv(result("V2_LDA_Topics.csv"))
bertopic_info = load_csv(result("V2_BERTopic_Info.csv"))
bertopic_words = load_csv(result("V2_BERTopic_Words.csv"))
social_bertopic = load_csv(result("V2_Social_BERTopic_Topics.csv"))

# ------------------------------------------------------------------
# Sidebar
# ------------------------------------------------------------------
st.sidebar.header("Inputs & filters")
st.sidebar.markdown(f"**Dataset:** `{DATASET_PATH.name}`")
if dataset is not None:
    st.sidebar.metric("Raw records", f"{len(dataset):,}")
if analyzed is not None:
    st.sidebar.metric("Analyzed records", f"{len(analyzed):,}")

year_min = int(dataset["Year"].min()) if dataset is not None and "Year" in dataset.columns else 2022
year_max = int(dataset["Year"].max()) if dataset is not None and "Year" in dataset.columns else 2026
year_range = st.sidebar.slider("Year range", year_min, year_max, (year_min, year_max))

show_raw = st.sidebar.checkbox("Show raw dataset table", value=False)
show_analyzed = st.sidebar.checkbox("Show analyzed records table", value=False)

# ------------------------------------------------------------------
# Tabs
# ------------------------------------------------------------------
tabs = st.tabs([
    "Overview",
    "Dataset",
    "Concepts & Dimensions",
    "Temporal Trends",
    "BERTopic & LDA",
    "Social Gap",
    "Saved Figures",
])

# ------------------------------------------------------------------
# Overview
# ------------------------------------------------------------------
with tabs[0]:
    st.header("Overview")
    if dataset is not None:
        col1, col2, col3, col4 = st.columns(4)
        col1.metric("Total papers", f"{len(dataset):,}")
        if "Year" in dataset.columns:
            col2.metric("Year span", f"{year_min} - {year_max}")
        if "Citation count" in dataset.columns:
            total_citations = dataset["Citation count"].sum()
            col3.metric("Total citations", f"{int(total_citations):,}")
        if analyzed is not None and "social_research_index" in analyzed.columns:
            top_social = (analyzed["social_research_index"] >= 50).sum()
            col4.metric("High social-relevance papers", f"{top_social:,}")

    if annual_growth is not None:
        st.subheader("Annual publication growth")
        fig = px.line(
            annual_growth,
            x="year",
            y="publications",
            markers=True,
            title="Publications per year",
            labels={"year": "Year", "publications": "Number of publications"},
        )
        fig.update_layout(height=450)
        st.plotly_chart(fig, use_container_width=True)

    st.subheader("Key findings")
    findings = []
    if dimensions is not None:
        edu = dimensions.loc[dimensions["dimension"] == "Educational/Adoption", "percentage"].values[0]
        soc = dimensions.loc[dimensions["dimension"] == "Social/Relational", "percentage"].values[0]
        findings.append(
            f"**Educational/Adoption** dominates the literature ({edu:.2f}%), "
            f"while **Social/Relational** dimensions cover only {soc:.2f}%."
        )
    if gap_test is not None:
        combined = gap_test.loc[gap_test["screen"] == "Either explicit OR semantic screen", "percentage"].values[0]
        findings.append(
            f"Combined explicit-lexical and top-10% semantic social screening "
            f"captures {combined:.2f}% of papers."
        )
    if social_summary is not None:
        very_high = social_summary[social_summary["gap_signal"] == "Very high"]["concept"].tolist()
        findings.append(
            "Social constructs with the strongest underrepresentation signal: "
            + ", ".join(very_high) + "."
        )
    for f in findings:
        st.markdown(f"- {f}")

# ------------------------------------------------------------------
# Dataset
# ------------------------------------------------------------------
with tabs[1]:
    st.header("Dataset")
    if dataset is not None:
        filtered = dataset[
            (dataset["Year"] >= year_range[0]) & (dataset["Year"] <= year_range[1])
        ].copy()
        st.metric("Selected records", f"{len(filtered):,}")

        if show_raw:
            st.subheader("Raw OpenAlex dataset")
            st.dataframe(filtered, use_container_width=True)

        st.subheader("Quick statistics")
        desc = pd.DataFrame({
            "column": dataset.columns,
            "non-null": dataset.notna().sum(),
            "missing": dataset.isna().sum(),
            "dtype": dataset.dtypes.astype(str),
        })
        st.dataframe(desc, use_container_width=True)

        if "Citation count" in dataset.columns:
            st.subheader("Top 20 most-cited papers")
            top = filtered.nlargest(20, "Citation count")[
                ["Title", "Author", "Year", "Citation count"]
            ].reset_index(drop=True)
            st.dataframe(top, use_container_width=True)
    else:
        st.warning("Raw dataset not found.")

    if analyzed is not None and show_analyzed:
        st.subheader("Analyzed records (V2)")
        st.dataframe(analyzed, use_container_width=True)

# ------------------------------------------------------------------
# Concepts & Dimensions
# ------------------------------------------------------------------
with tabs[2]:
    st.header("Concepts & Research Dimensions")

    col1, col2 = st.columns(2)
    with col1:
        if dimensions is not None:
            st.subheader("Five-dimensional coverage")
            fig = px.bar(
                dimensions.sort_values("percentage"),
                y="dimension",
                x="percentage",
                orientation="h",
                text="percentage",
                title="Literature coverage by dimension",
                labels={"percentage": "% of papers", "dimension": ""},
            )
            fig.update_traces(texttemplate="%{text:.2f}%", textposition="outside")
            fig.update_layout(height=400)
            st.plotly_chart(fig, use_container_width=True)

    with col2:
        if concept_freq is not None:
            st.subheader("Concept frequency")
            fig = px.bar(
                concept_freq.sort_values("percentage").tail(10),
                y="concept",
                x="percentage",
                orientation="h",
                text="percentage",
                title="Top 10 concepts by share",
                labels={"percentage": "% of papers", "concept": ""},
            )
            fig.update_traces(texttemplate="%{text:.2f}%", textposition="outside")
            fig.update_layout(height=400)
            st.plotly_chart(fig, use_container_width=True)

    if concept_freq is not None:
        st.subheader("All concept frequencies")
        st.dataframe(concept_freq, use_container_width=True)

    if tfidf is not None:
        st.subheader("Top TF-IDF terms")
        n_terms = st.slider("Number of terms", 10, 75, 25)
        st.dataframe(tfidf.head(n_terms), use_container_width=True)

# ------------------------------------------------------------------
# Temporal Trends
# ------------------------------------------------------------------
with tabs[3]:
    st.header("Temporal Trends")

    if annual_growth is not None:
        st.subheader("Publication growth")
        fig = px.bar(
            annual_growth,
            x="year",
            y="publications",
            title="Annual publications",
            labels={"publications": "Publications"},
        )
        st.plotly_chart(fig, use_container_width=True)

    if temporal is not None:
        st.subheader("Concept share over years")
        selected_concepts = st.multiselect(
            "Select concepts",
            options=sorted(temporal["concept"].unique()),
            default=[
                "Social/Relational" if "Social/Relational" in temporal["concept"].values else "Communication",
                "Education/Learning",
                "Ethics/Integrity",
            ],
        )
        if selected_concepts:
            sub = temporal[temporal["concept"].isin(selected_concepts)]
            fig = px.line(
                sub,
                x="year",
                y="percentage",
                color="concept",
                markers=True,
                title="Share of papers per concept by year",
                labels={"percentage": "% of papers"},
            )
            st.plotly_chart(fig, use_container_width=True)

    if social_temporal is not None:
        st.subheader("Social/relational attention over time")
        fig = go.Figure()
        fig.add_trace(
            go.Scatter(
                x=social_temporal["year"],
                y=social_temporal["lexical_pct"],
                mode="lines+markers",
                name="Explicit social terminology",
            )
        )
        fig.add_trace(
            go.Scatter(
                x=social_temporal["year"],
                y=social_temporal["combined_pct"],
                mode="lines+markers",
                name="Combined social screen",
            )
        )
        fig.update_layout(
            title="Social/relational research attention over time",
            xaxis_title="Year",
            yaxis_title="% of papers",
            height=450,
        )
        st.plotly_chart(fig, use_container_width=True)

    if emerging is not None:
        st.subheader("Emerging theme growth (change in annual share)")
        st.dataframe(emerging.sort_values("change_percentage_points", ascending=False), use_container_width=True)

# ------------------------------------------------------------------
# BERTopic & LDA
# ------------------------------------------------------------------
with tabs[4]:
    st.header("Topic Modeling")

    if bertopic_words is not None:
        st.subheader("BERTopic top words")
        st.dataframe(bertopic_words, use_container_width=True)

    if social_bertopic is not None:
        st.subheader("BERTopic topics ranked by social semantic similarity")
        fig = px.bar(
            social_bertopic,
            x="topic",
            y="social_semantic_similarity",
            hover_data=["papers", "top_words"],
            title="Topics by social semantic similarity",
            labels={"social_semantic_similarity": "Max cosine similarity"},
        )
        st.plotly_chart(fig, use_container_width=True)

    if bertopic_info is not None:
        st.subheader("BERTopic info")
        st.dataframe(
            bertopic_info[["Topic", "Count", "Name"]],
            use_container_width=True,
            column_config={"Name": st.column_config.TextColumn(width="large")},
        )

    if lda_topics is not None:
        st.subheader("LDA topics")
        st.dataframe(lda_topics, use_container_width=True)

# ------------------------------------------------------------------
# Social Gap
# ------------------------------------------------------------------
with tabs[5]:
    st.header("Social/Relational Gap Analysis")

    if gap_test is not None:
        st.subheader("Social gap test")
        col1, col2, col3 = st.columns(3)
        for i, row in gap_test.iterrows():
            if i == 0:
                col1.metric(row["screen"], f"{row['percentage']:.2f}%", f"{int(row['papers']):,} papers")
            elif i == 1:
                col2.metric(row["screen"], f"{row['percentage']:.2f}%", f"{int(row['papers']):,} papers")
            else:
                col3.metric(row["screen"], f"{row['percentage']:.2f}%", f"{int(row['papers']):,} papers")

        fig = px.bar(
            gap_test,
            x="screen",
            y="percentage",
            text="percentage",
            title="Social screening shares",
            labels={"screen": "Screen", "percentage": "% of papers"},
        )
        fig.update_traces(texttemplate="%{text:.2f}%", textposition="outside")
        st.plotly_chart(fig, use_container_width=True)

    if social_summary is not None:
        st.subheader("Social concept underrepresentation signal")
        fig = px.bar(
            social_summary.sort_values("percentage"),
            y="concept",
            x="percentage",
            color="gap_signal",
            orientation="h",
            text="percentage",
            title="Social concept coverage",
            labels={"percentage": "% of papers"},
        )
        fig.update_traces(texttemplate="%{text:.3f}%", textposition="outside")
        st.plotly_chart(fig, use_container_width=True)

    if analyzed is not None:
        st.subheader("Top social-relevance papers")
        top_n = st.slider("Number of papers", 5, 100, 15)
        cols = ["title", "year", "author", "social_research_index"]
        cols += [c for c in analyzed.columns if c.startswith("sim_")]
        available = [c for c in cols if c in analyzed.columns]
        top_social = analyzed.sort_values("social_research_index", ascending=False).head(top_n)[available]
        st.dataframe(top_social, use_container_width=True)

# ------------------------------------------------------------------
# Saved Figures
# ------------------------------------------------------------------
with tabs[6]:
    st.header("Saved Analysis Figures")
    fig_dir = RESULTS_DIR
    images = sorted(fig_dir.glob("*.png"))
    if images:
        for img in images:
            st.subheader(img.stem)
            display_img = Image.open(img) if Image is not None else str(img)
            try:
                st.image(display_img, use_container_width=True)
            except TypeError:
                st.image(display_img, use_column_width=True)
    else:
        st.info("No PNG figures found in Results/.")
