# -*- coding: utf-8 -*-
"""Generative_AI_University_Students_Research_Analysis_V2_FINAL.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pgznbSaeisCqvEaZ19yQKQYtFvVUEnIk

# FINAL VERSION 2 — Generative AI & University Students
## Bibliometric + NLP + BERTopic + Social/Interpersonal Research-Gap Validation

### Research objective
Map how Generative AI research involving university students has evolved and test whether **social, interpersonal, communication, connectedness, and human–AI relational dimensions** are comparatively underrepresented.

### Important
This is a **literature-level secondary-data study**. It does not establish that Generative AI causes changes in individual students.

### Main improvement over V1
The social-gap analysis does **not** depend on the phrase “social interaction.” It combines:
- concept dictionaries,
- separate social semantic queries,
- BERTopic,
- temporal proportions,
- co-occurrence networks,
- and manual-validation candidates.

The notebook also imports the previously generated `Social_Semantic_Candidates.csv` if you have it.
"""

# 1. Install packages
!pip -q install pandas numpy matplotlib scikit-learn openpyxl sentence-transformers umap-learn hdbscan bertopic networkx nltk

import os, re, warnings, math, json
warnings.filterwarnings("ignore")

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import networkx as nx

from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity
from sklearn.preprocessing import MinMaxScaler

print("Environment ready.")

"""# 2. Upload files

Upload:
1. **Required:** `OpenAlex_GenerativeAI_Students_Cleaned.csv`
2. **Optional:** `Social_Semantic_Candidates.csv`

If you do not have the second file, simply upload the cleaned OpenAlex CSV.

"""

from google.colab import files

uploaded = files.upload()

csv_files = [f for f in uploaded if f.lower().endswith(".csv")]
if not csv_files:
    raise ValueError("Please upload at least the OpenAlex CSV.")

openalex_candidates = [
    f for f in csv_files
    if "openalex" in f.lower() or "cleaned" in f.lower()
]

OPENALEX_FILE = openalex_candidates[0] if openalex_candidates else csv_files[0]
social_candidate_files = [f for f in csv_files if "social" in f.lower()]

df = pd.read_csv(OPENALEX_FILE, low_memory=False)

print("OpenAlex file:", OPENALEX_FILE)
print("Shape:", df.shape)
print("Optional social candidates:", social_candidate_files)

# 3. Normalize and detect columns

df.columns = [
    re.sub(r"[^a-z0-9]+", "_", str(c).strip().lower()).strip("_")
    for c in df.columns
]

def find_col(candidates):
    for c in candidates:
        if c in df.columns:
            return c
    return None

title_col = find_col(["title"])
abstract_col = find_col(["abstract", "abstracts"])
author_col = find_col(["author", "authors"])
year_col = find_col(["year", "publication_year"])
citation_col = find_col(["citation_count", "cited_by_count", "cited_by"])
doi_col = find_col(["doi"])
source_col = find_col(["source", "journal", "source_title"])

print({
    "title": title_col,
    "abstract": abstract_col,
    "authors": author_col,
    "year": year_col,
    "citations": citation_col,
    "doi": doi_col,
    "source": source_col
})

if not title_col or not abstract_col:
    raise ValueError("Title and Abstract columns are required.")

"""# 4. Clean and deduplicate

"""

data = df.copy()

data = data[data[title_col].notna()].copy()
data[title_col] = data[title_col].astype(str).str.strip()
data[abstract_col] = data[abstract_col].fillna("").astype(str)

data["_title_norm"] = (
    data[title_col].str.lower()
    .str.replace(r"[^a-z0-9 ]+", " ", regex=True)
    .str.replace(r"\s+", " ", regex=True)
    .str.strip()
)

before = len(data)
data = data.drop_duplicates("_title_norm", keep="first").copy()

if year_col:
    data[year_col] = pd.to_numeric(data[year_col], errors="coerce")

if citation_col:
    data["_citations"] = pd.to_numeric(data[citation_col], errors="coerce").fillna(0)

data["_text"] = (
    data[title_col].fillna("") + ". " + data[abstract_col].fillna("")
).str.strip()

print("Records before title deduplication:", before)
print("Unique records:", len(data))
print("Records with usable abstracts:", (data[abstract_col].str.len() >= 50).sum())

"""# 5. Dataset audit

"""

audit = pd.DataFrame({
    "metric": [
        "Initial records",
        "Unique records",
        "Duplicate titles removed",
        "Missing abstracts",
        "Usable abstracts (>=50 chars)",
        "Missing authors",
        "Missing year",
        "Missing citation count"
    ],
    "value": [
        len(df),
        len(data),
        before - len(data),
        int(data[abstract_col].str.len().eq(0).sum()),
        int((data[abstract_col].str.len() >= 50).sum()),
        int(data[author_col].isna().sum()) if author_col else np.nan,
        int(data[year_col].isna().sum()) if year_col else np.nan,
        int(data[citation_col].isna().sum()) if citation_col else np.nan
    ]
})

display(audit)

"""# 6. Publication growth and citation profile

"""

if year_col:
    annual = (
        data.dropna(subset=[year_col])
        .groupby(year_col)
        .size()
        .reset_index(name="publications")
    )
    annual[year_col] = annual[year_col].astype(int)
    annual = annual.sort_values(year_col)

    display(annual)

    plt.figure(figsize=(11,6))
    plt.plot(annual[year_col], annual["publications"], marker="o")
    plt.xlabel("Year")
    plt.ylabel("Publications")
    plt.title("Annual Publication Growth")
    plt.grid(alpha=0.2)
    plt.tight_layout()
    plt.savefig("V2_annual_publication_growth.png", dpi=300, bbox_inches="tight")
    plt.show()

if citation_col:
    top_cited = data.sort_values("_citations", ascending=False).head(25)
    show = [c for c in [title_col, author_col, year_col, citation_col, source_col, doi_col] if c]
    display(top_cited[show].reset_index(drop=True))

"""# 7. Expanded concept dictionary

The social domain is deliberately divided into multiple constructs so that one keyword cannot dominate the conclusion.

"""

concepts = {
    "Education/Learning": [
        "education","learning","teaching","instruction","learning outcome",
        "pedagogy","higher education","classroom","student learning"
    ],
    "Adoption/Acceptance": [
        "acceptance","adoption","intention to use","technology acceptance",
        "behavioral intention","perceived usefulness","perceived ease of use"
    ],
    "Critical Thinking/Cognition": [
        "critical thinking","critical reasoning","reasoning","cognitive skill",
        "cognition","metacognition","higher order thinking","higher-order thinking",
        "problem solving","problem-solving","decision making","decision-making"
    ],
    "Creativity": [
        "creativity","creative thinking","creative problem solving",
        "creative problem-solving","originality","innovation"
    ],
    "AI Dependency": [
        "ai dependency","ai dependence","dependency on ai","dependence on ai",
        "reliance on ai","overreliance","over-reliance","automation bias"
    ],
    "Motivation/Engagement": [
        "motivation","engagement","self regulated learning",
        "self-regulated learning","academic engagement","learning motivation"
    ],
    "Psychological Well-being": [
        "anxiety","stress","fear","well-being","wellbeing","mental health",
        "confidence","self efficacy","self-efficacy","psychological"
    ],
    "Ethics/Integrity": [
        "academic integrity","plagiarism","academic dishonesty","cheating",
        "ethics","ethical","responsible ai","responsible artificial intelligence"
    ],
    "Privacy": [
        "privacy","data privacy","data protection","personal data","confidentiality"
    ],
    "Trust": [
        "trust in ai","trust in artificial intelligence","trustworthy ai",
        "trusting ai","trust"
    ],
    "Communication": [
        "communication","communicative","communication skills",
        "written communication","verbal communication","interpersonal communication"
    ],
    "Peer/Social Interaction": [
        "social interaction","peer interaction","peer relationship",
        "peer relationships","student collaboration","group interaction",
        "social behavior","social behaviour","classroom interaction",
        "peer collaboration","student interaction"
    ],
    "Interpersonal Relationships": [
        "interpersonal","interpersonal relationship","interpersonal relationships",
        "human relationship","human relationships","face to face",
        "face-to-face","person to person","human interaction"
    ],
    "Social Connectedness/Isolation": [
        "social connectedness","social connection","sense of belonging",
        "social isolation","social withdrawal","loneliness","lonely",
        "belongingness","social support"
    ],
    "Human-AI Relationship": [
        "ai companionship","artificial intelligence companionship",
        "emotional attachment","anthropomorphism","social presence",
        "human ai relationship","human-ai relationship","relational interaction",
        "emotional connection with ai"
    ]
}

def concept_mask(series, terms):
    escaped = [re.escape(t).replace(r"\ ", r"\s+") for t in terms]
    pattern = r"(?:" + "|".join(escaped) + r")"
    return series.str.contains(pattern, case=False, regex=True, na=False)

rows = []
for concept, terms in concepts.items():
    m = concept_mask(data["_text"], terms)
    rows.append({
        "concept": concept,
        "papers": int(m.sum()),
        "percentage": round(m.mean()*100, 3)
    })

concept_table = pd.DataFrame(rows).sort_values("papers", ascending=False)
display(concept_table)

"""# 8. Five-dimensional research landscape

"""

dimension_map = {
    "Educational/Adoption": ["Education/Learning","Adoption/Acceptance"],
    "Cognitive": ["Critical Thinking/Cognition","Creativity"],
    "Behavioral": ["AI Dependency","Motivation/Engagement"],
    "Psychological/Ethical": ["Psychological Well-being","Trust","Ethics/Integrity","Privacy"],
    "Social/Relational": [
        "Communication","Peer/Social Interaction","Interpersonal Relationships",
        "Social Connectedness/Isolation","Human-AI Relationship"
    ]
}

dimension_rows = []
for dimension, subs in dimension_map.items():
    combined = pd.Series(False, index=data.index)
    for sub in subs:
        combined = combined | concept_mask(data["_text"], concepts[sub])
    dimension_rows.append({
        "dimension": dimension,
        "papers": int(combined.sum()),
        "percentage": round(combined.mean()*100, 3)
    })

dimension_table = pd.DataFrame(dimension_rows).sort_values("papers", ascending=False)
display(dimension_table)

plt.figure(figsize=(10,6))
p = dimension_table.sort_values("papers")
plt.barh(p["dimension"], p["papers"])
plt.xlabel("Papers")
plt.title("Literature Coverage by Research Dimension")
plt.tight_layout()
plt.savefig("V2_dimension_coverage.png", dpi=300, bbox_inches="tight")
plt.show()

"""# 9. Temporal concept analysis

Because the literature grows rapidly, **percentage of papers per year** is more informative than raw counts.

"""

if year_col:
    temporal_rows = []

    for concept, terms in concepts.items():
        m = concept_mask(data["_text"], terms)
        tmp = pd.DataFrame({"year": data[year_col], "match": m.astype(int)}).dropna()
        g = tmp.groupby("year").agg(
            total=("match","size"),
            papers=("match","sum")
        ).reset_index()
        g["percentage"] = g["papers"] / g["total"] * 100
        g["concept"] = concept
        temporal_rows.append(g)

    temporal = pd.concat(temporal_rows, ignore_index=True)
    temporal["year"] = temporal["year"].astype(int)

    social = [
        "Communication","Peer/Social Interaction","Interpersonal Relationships",
        "Social Connectedness/Isolation","Human-AI Relationship"
    ]

    plt.figure(figsize=(12,7))
    for c in social:
        s = temporal[temporal["concept"] == c]
        plt.plot(s["year"], s["percentage"], marker="o", label=c)

    plt.xlabel("Year")
    plt.ylabel("Share of papers (%)")
    plt.title("Evolution of Social/Relational Research Attention")
    plt.legend()
    plt.grid(alpha=0.2)
    plt.tight_layout()
    plt.savefig("V2_social_temporal_evolution.png", dpi=300, bbox_inches="tight")
    plt.show()

    display(
        temporal[temporal["concept"].isin(social)]
        .pivot(index="year", columns="concept", values="percentage")
        .round(3)
    )

"""# 10. TF-IDF

"""

tfidf = TfidfVectorizer(
    stop_words="english",
    ngram_range=(1,2),
    min_df=5,
    max_df=0.85,
    max_features=8000
)

X_tfidf = tfidf.fit_transform(data["_text"])
terms = np.array(tfidf.get_feature_names_out())
scores = np.asarray(X_tfidf.mean(axis=0)).ravel()

tfidf_table = (
    pd.DataFrame({"term": terms, "tfidf_mean": scores})
    .sort_values("tfidf_mean", ascending=False)
    .head(75)
)

display(tfidf_table)

"""# 11. LDA topic modeling

"""

count_vectorizer = CountVectorizer(
    stop_words="english",
    ngram_range=(1,2),
    min_df=8,
    max_df=0.90,
    max_features=10000
)

X_count = count_vectorizer.fit_transform(data["_text"])
feature_names = count_vectorizer.get_feature_names_out()

from sklearn.decomposition import LatentDirichletAllocation

N_TOPICS = 10
lda = LatentDirichletAllocation(
    n_components=N_TOPICS,
    random_state=42,
    learning_method="batch",
    max_iter=40
)

lda_doc_topic = lda.fit_transform(X_count)

lda_rows = []
for i, topic in enumerate(lda.components_):
    idx = topic.argsort()[:-16:-1]
    lda_rows.append({
        "topic": i+1,
        "top_words": ", ".join(feature_names[idx])
    })

lda_topics = pd.DataFrame(lda_rows)
display(lda_topics)

data["lda_topic"] = lda_doc_topic.argmax(axis=1) + 1
lda_distribution = data["lda_topic"].value_counts().sort_index()
display(lda_distribution.to_frame("papers"))

"""# 12. BERTopic semantic analysis

This is the main semantic topic model. It can identify conceptually similar papers even when they use different vocabulary.

"""

from sentence_transformers import SentenceTransformer
from bertopic import BERTopic

embedding_model = SentenceTransformer("all-MiniLM-L6-v2")

texts = data["_text"].tolist()

embeddings = embedding_model.encode(
    texts,
    batch_size=32,
    show_progress_bar=True,
    normalize_embeddings=True
)

print("Embeddings:", embeddings.shape)

topic_model = BERTopic(
    embedding_model=embedding_model,
    min_topic_size=30,
    nr_topics="auto",
    calculate_probabilities=True,
    verbose=True
)

bertopic_topics, bertopic_probs = topic_model.fit_transform(
    texts, embeddings
)

data["bertopic_topic"] = bertopic_topics

bertopic_info = topic_model.get_topic_info()
display(bertopic_info.head(30))

bertopic_words = []

for topic_id in bertopic_info["Topic"]:
    if topic_id == -1:
        continue
    words = topic_model.get_topic(topic_id)
    if words:
        bertopic_words.append({
            "topic": topic_id,
            "top_words": ", ".join([w for w, s in words[:15]])
        })

bertopic_words = pd.DataFrame(bertopic_words)
display(bertopic_words)

"""# 13. Social semantic analysis — corrected version

We use **five independent queries** instead of one broad query.

This is specifically designed to avoid the V1 problem where generic "student/ChatGPT perception" papers dominated the results.

"""

social_queries = {
    "Peer interaction": (
        "university students peer interaction peer relationships "
        "student collaboration group interaction classroom interaction"
    ),
    "Interpersonal communication": (
        "university students interpersonal communication human communication "
        "face to face communication communication skills relationships"
    ),
    "Social connectedness": (
        "university students social connectedness belonging loneliness "
        "social isolation social withdrawal social support"
    ),
    "Human-AI relationship": (
        "human AI relationship AI companionship emotional attachment "
        "anthropomorphism social presence relational interaction"
    ),
    "Social behavior": (
        "university students social behavior interpersonal behavior "
        "relationship behavior social conduct human interaction"
    )
}

query_embeddings = embedding_model.encode(
    list(social_queries.values()),
    normalize_embeddings=True
)

social_sim_matrix = cosine_similarity(query_embeddings, embeddings)

for i, name in enumerate(social_queries):
    safe = re.sub(r"[^a-z0-9]+", "_", name.lower()).strip("_")
    data[f"sim_{safe}"] = social_sim_matrix[i]

sim_cols = [c for c in data.columns if c.startswith("sim_")]

data["social_max_similarity"] = data[sim_cols].max(axis=1)
data["social_mean_similarity"] = data[sim_cols].mean(axis=1)

social_candidates_v2 = data.sort_values(
    ["social_max_similarity","social_mean_similarity"],
    ascending=False
).head(300).copy()

display(
    social_candidates_v2[
        [c for c in [title_col, year_col, author_col, abstract_col, doi_col] if c]
        + sim_cols
        + ["social_max_similarity","social_mean_similarity"]
    ].head(50)
)

"""# 14. Social Research Index

The index is a transparent screening device, **not a validated psychological scale**.

It combines:
- explicit social terminology,
- semantic social similarity,
- and the breadth of social dimensions represented.

"""

social_concepts = [
    "Communication",
    "Peer/Social Interaction",
    "Interpersonal Relationships",
    "Social Connectedness/Isolation",
    "Human-AI Relationship"
]

# Create binary flags for each social concept
social_flags = []

for c in social_concepts:
    flag = concept_mask(data["_text"], concepts[c]).astype(int)
    social_flags.append(flag)

# Combine flags
social_flag_matrix = pd.concat(social_flags, axis=1)
social_flag_matrix.columns = social_concepts

# IMPORTANT:
# Add the social concept columns to the main data frame
for c in social_concepts:
    data[c] = social_flag_matrix[c]

# Count how many different social dimensions each paper contains
data["social_concept_count"] = social_flag_matrix.sum(axis=1)

# Explicit lexical social indicator
data["social_lexical_flag"] = (
    data["social_concept_count"] >= 1
).astype(int)

# Semantic percentile
data["social_semantic_percentile"] = (
    data["social_max_similarity"].rank(pct=True)
)

# Breadth across the five social dimensions
data["social_breadth"] = (
    data["social_concept_count"] / len(social_concepts)
).clip(0, 1)

# Combined Social Research Index
data["social_research_index"] = (
    35 * data["social_lexical_flag"]
    + 45 * data["social_semantic_percentile"]
    + 20 * data["social_breadth"]
)

# Display top 50 social-relevant papers
display_cols = [
    c for c in [
        title_col,
        year_col,
        author_col,
        abstract_col
    ]
    if c
]

display_cols += social_concepts

display_cols += [
    "social_concept_count",
    "social_semantic_percentile",
    "social_breadth",
    "social_research_index"
]

result_social = (
    data
    .sort_values(
        "social_research_index",
        ascending=False
    )
    [display_cols]
    .head(50)
)

display(result_social)

"""# 15. Test whether the apparent social gap persists

We compare explicit lexical social evidence with the semantic tail.

**Important:** The semantic threshold is a screening threshold, not a claim that the top 10% are "social papers."

"""

social_lexical = data["social_lexical_flag"].astype(bool)
semantic_90 = data["social_max_similarity"].quantile(0.90)
semantic_top10 = data["social_max_similarity"] >= semantic_90

combined_social = social_lexical | semantic_top10

gap_test = pd.DataFrame({
    "screen": [
        "Explicit social terminology",
        "Top 10% semantic social similarity",
        "Either explicit OR semantic screen"
    ],
    "papers": [
        int(social_lexical.sum()),
        int(semantic_top10.sum()),
        int(combined_social.sum())
    ],
    "percentage": [
        round(social_lexical.mean()*100, 2),
        round(semantic_top10.mean()*100, 2),
        round(combined_social.mean()*100, 2)
    ]
})

display(gap_test)

print("90th percentile semantic threshold:", round(float(semantic_90), 4))

"""# 16. Social concept co-occurrence network

"""

G = nx.Graph()

valid = [c for c in social_concepts if social_flag_matrix[c].sum() >= 3]

for c in valid:
    G.add_node(c, frequency=int(social_flag_matrix[c].sum()))

for i, c1 in enumerate(valid):
    for c2 in valid[i+1:]:
        co = int((social_flag_matrix[c1] & social_flag_matrix[c2]).sum())
        if co >= 2:
            G.add_edge(c1, c2, weight=co)

print("Social concept nodes:", G.number_of_nodes())
print("Social concept edges:", G.number_of_edges())

if G.number_of_nodes() > 0:
    plt.figure(figsize=(11,9))
    pos = nx.spring_layout(G, seed=42, k=1.4)

    nx.draw_networkx(
        G, pos,
        with_labels=True,
        node_size=[G.nodes[n]["frequency"]*30 for n in G.nodes],
        width=[G[u][v]["weight"] for u,v in G.edges],
        font_size=9
    )

    plt.title("Co-occurrence Network of Social/Relational Concepts")
    plt.axis("off")
    plt.tight_layout()
    plt.savefig("V2_social_concept_network.png", dpi=300, bbox_inches="tight")
    plt.show()

"""# 17. BERTopic social relevance

We compare each BERTopic cluster against the social query space.

"""

topic_docs = (
    data[data["bertopic_topic"] != -1]
    .groupby("bertopic_topic")["_text"]
    .apply(lambda x: " ".join(x.head(50).tolist()))
)

topic_ids = topic_docs.index.tolist()
topic_embeddings = embedding_model.encode(
    topic_docs.tolist(),
    normalize_embeddings=True
)

topic_social_sim = cosine_similarity(
    query_embeddings,
    topic_embeddings
).max(axis=0)

social_topic_table = pd.DataFrame({
    "topic": topic_ids,
    "social_semantic_similarity": topic_social_sim
})

social_topic_table = (
    social_topic_table
    .merge(
        bertopic_info[["Topic","Count"]].rename(
            columns={"Topic":"topic","Count":"papers"}
        ),
        on="topic",
        how="left"
    )
    .merge(bertopic_words, on="topic", how="left")
    .sort_values("social_semantic_similarity", ascending=False)
)

display(social_topic_table.head(20))

"""# 18. Social attention over time

This is one of the most important analyses for the final paper.

"""

if year_col:
    temp = data[[year_col, "social_lexical_flag",
                 "social_max_similarity"]].copy()

    temp["semantic_top10"] = semantic_top10.astype(int).values
    temp["combined_social"] = combined_social.astype(int).values

    yearly_social = temp.groupby(year_col).agg(
        total_papers=(year_col,"size"),
        lexical_social=("social_lexical_flag","sum"),
        semantic_top10=("semantic_top10","sum"),
        combined_social=("combined_social","sum"),
        mean_social_similarity=("social_max_similarity","mean")
    ).reset_index()

    yearly_social["lexical_pct"] = (
        yearly_social["lexical_social"] /
        yearly_social["total_papers"] * 100
    )

    yearly_social["combined_pct"] = (
        yearly_social["combined_social"] /
        yearly_social["total_papers"] * 100
    )

    display(yearly_social)

    plt.figure(figsize=(11,6))
    plt.plot(
        yearly_social[year_col],
        yearly_social["lexical_pct"],
        marker="o",
        label="Explicit social terminology"
    )
    plt.plot(
        yearly_social[year_col],
        yearly_social["combined_pct"],
        marker="o",
        label="Combined social screen"
    )
    plt.xlabel("Year")
    plt.ylabel("Share of papers (%)")
    plt.title("Social/Relational Research Attention Over Time")
    plt.legend()
    plt.grid(alpha=0.2)
    plt.tight_layout()
    plt.savefig("V2_social_gap_over_time.png", dpi=300, bbox_inches="tight")
    plt.show()

"""# 19. Emerging themes: growth in annual share

Raw counts are strongly affected by the explosive growth of the corpus. We therefore rank themes by change in their annual percentage share.

"""

if year_col:
    growth_rows = []

    for concept in concepts:
        s = temporal[temporal["concept"] == concept].sort_values("year")

        # Compare earliest and latest available year, but report the values.
        if len(s) >= 2:
            first = s.iloc[0]
            last = s.iloc[-1]

            growth_rows.append({
                "concept": concept,
                "first_year": int(first["year"]),
                "first_share_pct": round(first["percentage"], 3),
                "last_year": int(last["year"]),
                "last_share_pct": round(last["percentage"], 3),
                "change_percentage_points": round(
                    last["percentage"] - first["percentage"], 3
                )
            })

    growth_table = pd.DataFrame(growth_rows).sort_values(
        "change_percentage_points", ascending=False
    )

    display(growth_table)

"""# 20. Optional: inspect the previously generated V1 social candidates

If `Social_Semantic_Candidates.csv` was uploaded, this section displays it for comparison. It is **not treated as final evidence**.

"""

if social_candidate_files:
    v1_social = pd.read_csv(social_candidate_files[0], low_memory=False)
    print("V1 candidate file:", social_candidate_files[0])
    print("Rows:", len(v1_social))
    display(v1_social.head(30))
else:
    print("No V1 Social_Semantic_Candidates.csv uploaded; skipping comparison.")

"""# 21. Research-gap evidence table

This creates a concise table for manuscript development.

"""

social_concept_summary = concept_table[
    concept_table["concept"].isin(social_concepts)
].copy()

social_concept_summary["gap_signal"] = pd.cut(
    social_concept_summary["percentage"],
    bins=[-np.inf, 1, 3, 10, np.inf],
    labels=["Very high", "High", "Moderate", "Low"]
)

display(
    social_concept_summary.sort_values("percentage")
)

"""# 22. Export all results

The Excel workbook is the main output to upload back for interpretation.

"""

# Core exports
data.to_csv("V2_Analyzed_OpenAlex_GenerativeAI_Students.csv", index=False)
concept_table.to_csv("V2_Concept_Frequency.csv", index=False)
dimension_table.to_csv("V2_Dimension_Coverage.csv", index=False)
tfidf_table.to_csv("V2_TFIDF_Terms.csv", index=False)
lda_topics.to_csv("V2_LDA_Topics.csv", index=False)
bertopic_info.to_csv("V2_BERTopic_Info.csv", index=False)
bertopic_words.to_csv("V2_BERTopic_Words.csv", index=False)
social_candidates_v2.to_csv("V2_Social_Semantic_Candidates.csv", index=False)
social_topic_table.to_csv("V2_Social_BERTopic_Topics.csv", index=False)
gap_test.to_csv("V2_Social_Gap_Test.csv", index=False)
social_concept_summary.to_csv("V2_Social_Concept_Summary.csv", index=False)

if year_col:
    annual.to_csv("V2_Annual_Publication_Growth.csv", index=False)
    temporal.to_csv("V2_Concept_Temporal.csv", index=False)
    yearly_social.to_csv("V2_Social_Temporal.csv", index=False)
    growth_table.to_csv("V2_Emerging_Theme_Growth.csv", index=False)

with pd.ExcelWriter(
    "Generative_AI_University_Students_Research_Analysis_V2_FINAL.xlsx",
    engine="openpyxl"
) as writer:
    audit.to_excel(writer, sheet_name="Dataset_Audit", index=False)
    concept_table.to_excel(writer, sheet_name="Concept_Frequency", index=False)
    dimension_table.to_excel(writer, sheet_name="Dimensions", index=False)
    tfidf_table.to_excel(writer, sheet_name="TFIDF", index=False)
    lda_topics.to_excel(writer, sheet_name="LDA_Topics", index=False)
    lda_distribution.to_frame("papers").to_excel(writer, sheet_name="LDA_Distribution")
    bertopic_info.to_excel(writer, sheet_name="BERTopic_Info", index=False)
    bertopic_words.to_excel(writer, sheet_name="BERTopic_Words", index=False)
    social_topic_table.to_excel(writer, sheet_name="Social_BERTopic", index=False)
    social_candidates_v2.to_excel(writer, sheet_name="Social_Candidates", index=False)
    gap_test.to_excel(writer, sheet_name="Social_Gap_Test", index=False)
    social_concept_summary.to_excel(writer, sheet_name="Social_Summary", index=False)

    if year_col:
        annual.to_excel(writer, sheet_name="Annual_Growth", index=False)
        temporal.to_excel(writer, sheet_name="Concept_Temporal", index=False)
        yearly_social.to_excel(writer, sheet_name="Social_Temporal", index=False)
        growth_table.to_excel(writer, sheet_name="Emerging_Growth", index=False)

print("FINAL V2 workbook created.")

"""# 23. What to upload back for final research interpretation

Upload:

**`Generative_AI_University_Students_Research_Analysis_V2_FINAL.xlsx`**

I will then use the actual results to determine:

1. the final research gap,
2. whether the social/interpersonal novelty is defensible,
3. the best paper title,
4. research questions,
5. conceptual framework,
6. methodology,
7. hypotheses/propositions if appropriate,
8. key tables and figures,
9. and the target journal positioning.

### Do not make a novelty claim before this validation.

"""